//CONSTANTS FOR REDUCER ACTIONS
export const ADMIN_GET_DATA = "ADMIN_GET_DATA";
export const ADMIN_UPDATE_INFO = "ADMIN_UPDATE_INFO";

export const PRODUCTS_GET_ALL = "PRODUCTS_GET_ALL";
export const PRODUCTS_GET_PRODUCT = "PRODUCTS_GET_PRODUCT";

export const CATEGORY_GET_ALL = "CATEGORY_GET_ALL";
export const CATEGORY_GET_CATEGORY = "CATEGORY_GET_CATEGORY";