//CONSTANTS FOR REDUCER ACTIONS
export const ADMIN_GET_DATA = "ADMIN_GET_DATA";
export const ADMIN_UPDATE_INFO = "ADMIN_UPDATE_INFO";

export const PRODUCTS_GET_ALL = "PRODUCTS_GET_ALL";
export const PRODUCTS_GET_PRODUCT = "PRODUCTS_GET_PRODUCT";
export const PRODUCTS_ADD_PRODUCT = "PRODUCTS_ADD_PRODUCT";
export const PRODUCTS_DELETE_PRODUCT_SUCCESS = "PRODUCTS_DELETE_PRODUCT_SUCCESS";
export const PRODUCTS_DELETE_PRODUCT_FAILED = "PRODUCTS_DELETE_PRODUCT_FAILED";

export const CATEGORY_GET_ALL = "CATEGORY_GET_ALL";
export const CATEGORY_ADD_CATEGORY = "CATEGORY_ADD_CATEGORY";
export const CATEGORY_GET_CATEGORY = "CATEGORY_GET_CATEGORY";
export const CATEGORY_UPDATE_CATEGORY = "CATEGORY_UPDATE_CATEGORY";
export const CATEGORY_DELETE_CATEGORY = "CATEGORY_DELETE_CATEGORY";

export const SUBCATEGORY_GET_ALL = "SUBCATEGORY_GET_ALL";
export const SUBCATEGORY_GET_SUBCATEGORY = "SUBCATEGORY_GET_SUBCATEGORY";